spring:
  application:
    name: hello-service

  grpc:
    client:
      channels:
        local:
          address: "dns:///localhost:9090"
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8085