apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  namespace: grpc-hello-service
  labels:
    app: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      name: hello-service
      labels:
        app: hello-service
    spec:
      containers:
        - name: hello-service
          image: grpc-sample/hello-service:1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1M"
          ports:
            - containerPort: 8085
              protocol: TCP
          env:
            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_ADDRESS
              value: dns:///to-upper-case-service:9090
#            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_DEFAULT_LOAD_BALANCING_POLICY
#              value: "round_robin"
#            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_ENABLE_KEEP_ALIVE
#              value: "true"
#            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_ENABLE_KEEP_ALIVE_TIME
#              value: "1s"
#            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_ENABLE_KEEP_ALIVE_TIMEOUT
#              value: "1s"
#            - name: JAVA_TOOL_OPTIONS
#              value: "-Dnetworkaddress.cache.ttl=1 -Dio.grpc.internal.DnsNameResolverProvider.enable_srv=true -Dio.grpc.internal.DnsNameResolverProvider.refreshIntervalMs=10000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-upper-case-service
  namespace: grpc-hello-service
  labels:
    app: to-upper-case-service
spec:
  replicas: 10
  selector:
    matchLabels:
      app: to-upper-case-service
  template:
    metadata:
      name: to-upper-case-service
      labels:
        app: to-upper-case-service
    spec:
      containers:
        - name: to-upper-case-service
          image: grpc-sample/to-upper-case-service:1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1M"
          ports:
            - containerPort: 9090
              protocol: TCP
#          env:
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_TIME
#              value: "1s"
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_TIMEOUT
#              value: "1s"
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_MAX_IDLE
#              value: "1s"
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_MAX_AGE
#              value: "1s"
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_MAX_AGE_GRACE
#              value: "1s"