apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  namespace: grpc-hello-service
  labels:
    app: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      name: hello-service
      labels:
        app: hello-service
    spec:
      serviceAccountName: hello-service
      containers:
        - name: hello-service
          image: grpc-sample/hello-service:1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1M"
          ports:
            - containerPort: 8085
              protocol: TCP
          env:
            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_ADDRESS
              value: k8s:///to-upper-case-service:9090
            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_DEFAULT_LOAD_BALANCING_POLICY
              value: "round_robin"
#            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_ENABLE_KEEP_ALIVE
#              value: "true"
#            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_ENABLE_KEEP_ALIVE_TIME
#              value: "1s"
#            - name: SPRING_GRPC_CLIENT_CHANNELS_LOCAL_ENABLE_KEEP_ALIVE_TIMEOUT
#              value: "1s"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-upper-case-service
  namespace: grpc-hello-service
  labels:
    app: to-upper-case-service
spec:
  replicas: 20
  selector:
    matchLabels:
      app: to-upper-case-service
  template:
    metadata:
      name: to-upper-case-service
      labels:
        app: to-upper-case-service
    spec:
      containers:
        - name: to-upper-case-service
          image: grpc-sample/to-upper-case-service:1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1M"
          ports:
            - containerPort: 9090
              protocol: TCP
#          env:
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_TIME
#              value: "1s"
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_TIMEOUT
#              value: "1s"
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_MAX_IDLE
#              value: "1s"
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_MAX_AGE
#              value: "1s"
#            - name: SPRING_GRPC_SERVER_KEEP_ALIVE_MAX_AGE_GRACE
#              value: "1s"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-service
  namespace: grpc-hello-service

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: endpoint-watcher
  namespace: grpc-hello-service
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-service-endpoint-watcher
  namespace: grpc-hello-service
subjects:
  - kind: ServiceAccount
    name: hello-service
    namespace: grpc-hello-service
roleRef:
  kind: Role
  name: endpoint-watcher
  apiGroup: rbac.authorization.k8s.io